// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using storage;

namespace storage.Migrations
{
    [DbContext(typeof(WorkOutBuddyContext))]
    [Migration("20211016161108_CardModel")]
    partial class CardModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("domain.models.AccountModel", b =>
                {
                    b.Property<int>("EnitityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnitityId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            EnitityId = -1,
                            DateJoined = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Taylor@live.com",
                            FirstName = "Taylor",
                            LastName = "Stoltzfus"
                        },
                        new
                        {
                            EnitityId = -2,
                            DateJoined = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Faker@live.com",
                            FirstName = "James",
                            LastName = "Stoltzfus"
                        });
                });

            modelBuilder.Entity("domain.models.CardModel", b =>
                {
                    b.Property<int>("EnitityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManaCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerToughness")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnitityId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            EnitityId = 1,
                            CardType = "Instant",
                            ImagePath = "https://www.google.com/search?tbs=sbi:AMhZZivdILz9U0HsPhVAibP0jYIrjMxd8mFfMqs4fJyBH5hDBD8PvaTs3vbffBYMAsMRTysDIfxko5FG04feQrF4Px7dtvvCXJmr0_1NZDX_1NfJAKpMYRto_14Cu--Lktu1nT2kFB5OFshEvyc9QMJsFMioUSxfwxXY0jJEeGnNsRFJn8LsKzU3Y3L-FsiZ6q2oikJhMMxNQHZrhghNbXIzkXP0eSKZRujSm19dXWjO8aydqb300XNbUFev3ZojsE8wRs2wo-ecol1NyJLeOX0l3_1PNld3uankMqDgMAqthmqACqt8c7qFn7jN84mTiADso-2KFlP5gUXRewCKB9M0YbNF2NuyCbdm6FkmyKVdYjzBKCEB7NKMyzuXKlzfV_1OaFipiYGCxR4ZO99jMwOR8YYPQHD3juzEHzw",
                            ManaCost = "R",
                            Name = "Lightning Bolt",
                            PowerToughness = "N/A"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
